// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Blobs          string
	Documents      string
	DocumentsBlobs string
	DocumentsTags  string
	Projects       string
	Tags           string
	Taxonomies     string
}{
	Blobs:          "blobs",
	Documents:      "documents",
	DocumentsBlobs: "documents_blobs",
	DocumentsTags:  "documents_tags",
	Projects:       "projects",
	Tags:           "tags",
	Taxonomies:     "taxonomies",
}
